In [43]:
import numpy as np

wa = np.array([[0, 0, 0, 0]])

wa = np.append(wa, [[1, 1, 1, 1]], axis = 0)
wa = np.append(wa, [[2, 2, 2, 2]], axis = 0)

print(wa)

print(wa.shape[0])

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
3


In [28]:
def pos(string, percentage) :
	
	if string == 'width' :
		length = globals()['width_size']
		
	elif string == 'height' :
		length = globals()['height_size']
		
	else :
		print('wrong string argument, {}'.format(string))
	
	return percentage * (1/1000) * length
		
def width(percentage) :
	exact_pos = pos('width', percentage)
	return exact_pos

def height(percentage) :
	exact_pos = pos('height', percentage)
	return exact_pos

In [37]:
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt
import imodule as imd

size = [pow(10, 4), pow(10, 4)]
square = [200, 20, 800, 1000] # left x, left y, right x, right y
name = 'temp'

# (width, height) 크기의 빈 이미지와
# 그 이미지 위에 도형을 그릴 수 있는 툴


global width_size
global height_size

width_size = size[0]
height_size = size[1]

print('width = {}, height = {}'.format(width_size, height_size))

image = Image.new(mode = 'P', size = (width_size, height_size), color = 'white')
draw = ImageDraw.Draw(image)

width = 10000, height = 10000


In [40]:
def working_area(square, width, height, horizontal_buffer, vertical_buffer, \
				width_interval, height_interval, visualize) :
	print(square)    
	x0 = width(square[0])
	y0 = height(square[1])
	x1 = width(square[2])
	y1 = height(square[3])
	
	x0 += horizontal_buffer
	x1 += -1 * horizontal_buffer
	y0 += vertical_buffer
	y1 += -1 * vertical_buffer
	
	square = [x0, y0, x1, y1]
	
	if visualize == 1 :
		color = 'red'
	else :
		color = 'black'
		
	# adjust width_interval
	
	print('original width, width_interval = {}, {}'.format(width, width_interval))
	
	box_num_x = ((x1 - x0 + width_interval) / (width + width_interval)) // 1
	if box_num != 1 :
		width_interval = (x1 - x0 - box_num_x * width) / (box_num_x - 1)
	else :
		print('error : box number(x) must be bigger than 1')
	
	box_num_y = ((y1 - y0 + height_interval) / (height + height_interval)) // 1
	if box_num_y != 1 :
		height_interval = (y1 - y0 - box_num_y * height) / (box_num_y - 1)
	else :
		print('error : box number(y) must be bigger than 1')
	
	print('adjusted width, width_interval = {}, {}'.format(width, width_interval))
	
	# make workboxes
	box_left_x = [x0]
	box_left_y = [y0]
	
	x = x0
	y = y0
	
	while x < x1 :
		x += width + width_interval
		box_left_x.append(x)
		
	while y < y1 :
		y += height + height_interval
		box_left_y.append(y)
		
	box_xy = np.array([[0, 0, 0, 0]])
	
	for i in range(len(box_left_x)) :
		for j in range(len(box_left_y)) :
			xx0 = box_left_x[i]
			yy0 = box_left_y[j]
			xx1 = xx0 + width
			yy1 = yy0 + height
			
			box_xy = np.append(box_xy, [[xx0, yy0, xx1, yy1]], axis = 1)
		
	box_xy = box_xy[1 :]

	for i in range(box_xy.shape[0]) :
		print(box_xy[i])
	return box_xy

In [41]:
box = working_area(square, 30, 50, 100, 100, 10, 15, 1)

[200, 20, 800, 1000]


TypeError: 'int' object is not callable